<?php
/*
$arrDefaultArea = array(

	array('siteName' =>'Google谷歌' ,'siteUrl'=>'http://www.google.cn/search?hl=zh-CN&client=aff-avalanche&forid=1&channel=textlink&q='),
	array('siteName' =>'百度' ,'siteUrl'=>'http://www.baidu.com/'),
	array('siteName' =>'腾讯QQ' ,'siteUrl'=>'http://www.qq.com/'),
	array('siteName' =>'网易' ,'siteUrl'=>'http://www.163.com/'),
	array('siteName' =>'新浪' ,'siteUrl'=>'http://www.sina.com.cn/'),
	array('siteName' =>'搜狐' ,'siteUrl'=>'http://www.sohu.com/'),
	array('siteName' =>'雅虎' ,'siteUrl'=>'http://cn.yahoo.com/'),
	array('siteName' =>'MSN中文网' ,'siteUrl'=>'http://cn.msn.com/'),
	array('siteName' =>'中央电视台' ,'siteUrl'=>'http://www.cctv.com/'),
	array('siteName' =>'湖南卫视' ,'siteUrl'=>'http://www.hunantv.com/'),
	array('siteName' =>'凤凰网' ,'siteUrl'=>'http://www.ifeng.com/'),
	array('siteName' =>'TOM' ,'siteUrl'=>'http://www.tom.com/'),
	array('siteName' =>'猫扑' ,'siteUrl'=>'http://www.mop.com/'),
	array('siteName' =>'校内网' ,'siteUrl'=>'http://www.xiaonei.com/'),
	array('siteName' =>'易趣' ,'siteUrl'=>'http://www.eachnet.com/?adid=bjmt_mta_02_0_hp_1035'),
	array('siteName' =>'中国移动' ,'siteUrl'=>'http://www.chinamobile.com/'),
	array('siteName' =>'土豆网' ,'siteUrl'=>'http://www.tudou.com/'),
	array('siteName' =>'优酷网' ,'siteUrl'=>'http://www.youku.com/'),
	array('siteName' =>'开心网' ,'siteUrl'=>'http://www.kaixin001.com/'),
	array('siteName' =>'百度有啊' ,'siteUrl'=>'http://youa.baidu.com/'),
	array('siteName' =>'中华网' ,'siteUrl'=>'http://www.china.com/'),
	array('siteName' =>'汽车之家' ,'siteUrl'=>'http://www.autohome.com.cn/'),
	array('siteName' =>'东方财富网 ' ,'siteUrl'=>'http://www.eastmoney.com/'),
	array('siteName' =>'人民网' ,'siteUrl'=>'http://www.people.com.cn/'),
	array('siteName' =>'21CN' ,'siteUrl'=>'http://www.21cn.com/'),
	array('siteName' =>'中彩网' ,'siteUrl'=>'http://www.zhcw.com/'),
	array('siteName' =>'阿里巴巴' ,'siteUrl'=>'http://china.alibaba.com/?cosite=265dh&location=alihomepage_dh'),
	array('siteName' =>'早报网' ,'siteUrl'=>'http://www.zaobao.com/'),
	array('siteName' =>'浙江都市网' ,'siteUrl'=>'http://www.zj.com/'),
	array('siteName' =>'浙江在线' ,'siteUrl'=>'http://www.zjol.com.cn/'),
	array('siteName' =>'新华网' ,'siteUrl'=>'http://www.xinhuanet.com/'),
	array('siteName' =>'瑞丽女性网' ,'siteUrl'=>'http://www.rayli.com.cn/'),
	array('siteName' =>'搜房网' ,'siteUrl'=>'http://www.soufun.com/'),
	array('siteName' =>'电玩巴士' ,'siteUrl'=>'http://www.tgbus.com/'),
	array('siteName' =>'泡泡网' ,'siteUrl'=>'http://www.pcpop.com/'),
	array('siteName' =>'世纪佳缘' ,'siteUrl'=>'http://www.jiayuan.com/'),
	array('siteName' =>'聚 友 网' ,'siteUrl'=>'http://www.myspace.cn/'),
	array('siteName' =>'51个人空间' ,'siteUrl'=>'http://www.51.com/'),
	array('siteName' =>'太平洋电脑网' ,'siteUrl'=>'http://www.pconline.com.cn/'),
	array('siteName' =>'中国政府网' ,'siteUrl'=>'http://www.gov.cn/'),
	array('siteName' =>'淘宝网' ,'siteUrl'=>'http://www.taobao.com/'),
	array('siteName' =>'卓越网上购物' ,'siteUrl'=>'http://www.amazon.cn/?source=2006adhao123famousdaohang'),
	array('siteName' =>'中华英才网' ,'siteUrl'=>'http://www.chinahr.com/'),
	array('siteName' =>'智联招聘' ,'siteUrl'=>'http://www.zhaopin.com'),
	
	array('siteName' =>'中国万网' ,'siteUrl'=>'http://www.net.cn/'),
	array('siteName' =>'12530彩铃' ,'siteUrl'=>'http://www.12530.com/newweb/index/home/4060/4060/hao123/p.html'),
	array('siteName' =>'申通快递' ,'siteUrl'=>'http://www.sto.cn/'),
	array('siteName' =>'清华大学' ,'siteUrl'=>'http://www.tsinghua.edu.cn/'),
	array('siteName' =>'携程旅行网' ,'siteUrl'=>'http://www.ctrip.com/'),
	
	array('siteName' =>'工商银行' ,'siteUrl'=>'http://www.icbc.com.cn/'),
	array('siteName' =>'建设银行' ,'siteUrl'=>'http://www.ccb.com/'),
	array('siteName' =>'大众点评网' ,'siteUrl'=>'http://www.dianping.com/'),
	
	array('siteName' =>'天涯社区' ,'siteUrl'=>'http://www.tianya.cn/'),
	array('siteName' =>'和讯网' ,'siteUrl'=>'http://www.hexun.com/'),
	
	
);
*/
$arrDefaultArea = array(
    array('siteName' =>'天气预报-预报七天' ,'siteUrl'=>'http://weather.news.sina.com.cn'),
    array('siteName' =>'国内列车时刻表查询' ,'siteUrl'=>'#'),
    array('siteName' =>'论坛转贴工具' ,'siteUrl'=>''),
    array('siteName' =>'手机号码所在地区查询' ,'siteUrl'=>'http://www.showji.com'),
    array('siteName' =>'阴阳转换万年历' ,'siteUrl'=>''),
    array('siteName' =>'汉字简体繁体转换' ,'siteUrl'=>''),
    array('siteName' =>'EMS查询' ,'siteUrl'=>''),
    array('siteName' =>'国内国际机票查询' ,'siteUrl'=>''),
    array('siteName' =>'手机型号大全查询' ,'siteUrl'=>''),
    array('siteName' =>'五笔编码拼音查询' ,'siteUrl'=>''),
    array('siteName' =>'在线翻译' ,'siteUrl'=>''),
    array('siteName' =>'货币汇率兑换' ,'siteUrl'=>''),
    array('siteName' =>'在线度衡量转换器' ,'siteUrl'=>''),
    array('siteName' =>'邮编查询区号查询' ,'siteUrl'=>''),
    array('siteName' =>'身份证号码查询验证' ,'siteUrl'=>''),
    array('siteName' =>'全国各地车牌查询表' ,'siteUrl'=>''),
    array('siteName' =>'快递查询' ,'siteUrl'=>''),
);

$arrSearchBy = array("2"=>"=",
					 "1"=>"&gt;=",
					 "0"=>"&lt;=");
?>